Cholrang
Seojeil/team_10-_spartamarket pull request #26
Opened 2024-08-25 12:04 UTC by Limsunoh

add : 프로필 사진 기본값 설정 및 사진변경 기능구현
fix: 비밀번호 변경시 에러나는거 수정

2024-08-25 12:05 UTC, jung-sungwon approved these changes
실시간 확인 했습니다 ㅋㅋㅋ

2024-08-25 12:29 UTC, Seojeil requested changes
주말인데도 많이 작업하셨네요.
수고하셨습니다!!!
다만 .gitignore에 유저별 프로필 사진을 저장하는 경로를 추가해주셔야할것같아요
귀여운 강아지 사진을 못보게 되는건 아쉽지만 데이터베이스에 연동된 데이터라 다른 분의 컴퓨터에서는 사용하지 못하고 용량만 차지하는 데이터라서요.
디폴트이미지만 남겨주시면 감사하겠습니다!!

2024-08-25 12:29 UTC, Seojeil commented on spartamarket/accounts/models.py
>      #     blank=True
이 부분은 사용안하셨다면 삭제하셔도 상관없습니다.

2024-08-25 12:40 UTC, Limsunoh commented on spartamarket/accounts/models.py
>      #     blank=True
네 변경 후 다시  pull request 하겠습니다. 
지금은 동작엔 문제가 없으니 내일 push 할때 추가하도록 해도될까요?

2024-08-25 12:48 UTC, Seojeil commented on spartamarket/accounts/models.py
>      #     blank=True
넹 merge만 안하시면 돼요!!
다시 한번 수고하셨어요!!!

2024-08-26 00:12 UTC, l-yoon approved these changes
확인했습니다!

2024-08-26 12:28 UTC, closed without merging